version: "3.1"
services:
  db:
    image: postgres:15.4
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DEFAULT_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  dbdata:
